ip_iface:
  - name: Vlan20
    ip: 10.0.0.1
    mask: 255.255.255.0
  - name: Vlan21
    ip: 10.0.1.1
    mask: 255.255.255.0

iface:
  - name: GigabitEthernet0/2
    desc: "Trunk"
    mode: trunk
    a_vlan: 1
  - name: GigabitEthernet0/3
    desc: "Trunk"
    mode: trunk
    a_vlan: 1